name: PR Automated Tests

on:
  pull_request:
    branches:
      - Test
  workflow_dispatch:

jobs:
  automated-tests:
    name: Run Automated Tests
    uses: microsoft/AL-Go-Actions/.github/workflows/Test.yml@v8.3
    with:
      environmentName: PT_SBOX
    secrets: inherit
